from pathlib import Path
from typing import BinaryIO, Protocol


class StorageAdapter(Protocol):
    def create_storage_key(self, extension: str) -> str: ...

    def save_temporary(self, source: BinaryIO) -> Path: ...

    def finalize(self, temporary_path: Path, storage_key: str) -> None: ...

    def delete_temporary(self, temporary_path: Path) -> None: ...

    def delete(self, storage_key: str) -> None: ...

    def exists(self, storage_key: str) -> bool: ...

    def read(self, storage_key: str) -> bytes: ...
